amrikyy_travel_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') | as_number }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1

    prod:
      type: postgres
      host: "{{ env_var('DB_HOST_PROD') }}"
      port: "{{ env_var('DB_PORT_PROD') | as_number }}"
      user: "{{ env_var('DB_USER_PROD') }}"
      password: "{{ env_var('DB_PASSWORD_PROD') }}"
      dbname: "{{ env_var('DB_NAME_PROD') }}"
      schema: analytics
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1