# Prometheus Configuration for Maya Travel Agent
# Scrapes metrics from backend and frontend services

global:
  scrape_interval: 15s # Scrape every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  external_labels:
    monitor: 'maya-travel-agent'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'

# Load rules once and periodically evaluate them
rule_files:
  - 'alerts.yml'

# Scrape configurations
scrape_configs:
  # Backend API metrics
  - job_name: 'maya-backend'
    static_configs:
      - targets: ['localhost:3001']
        labels:
          service: 'backend'
          component: 'api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Frontend metrics (if applicable)
  - job_name: 'maya-frontend'
    static_configs:
      - targets: ['localhost:3000']
        labels:
          service: 'frontend'
          component: 'web'
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 5s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          component: 'system'
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          component: 'monitoring'

