services:
  - type: web
    name: amrikyy-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run start-backend"
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        fromDatabase:
          name: amrikyy-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false

databases:
  - name: amrikyy-db
    plan: free
