groups:
  - name: maya-travel-agent
    rules:
      # Application health alerts
      - alert: MayaTravelAgentDown
        expr: up{job="maya-travel-agent"} == 0
        for: 1m
        labels:
          severity: critical
          service: maya-travel-agent
        annotations:
          summary: "Maya Travel Agent is down"
          description: "Maya Travel Agent has been down for more than 1 minute."

      # High response time alerts
      - alert: HighResponseTime
        expr: http_request_duration_seconds{quantile="0.95"} > 3
        for: 5m
        labels:
          severity: warning
          service: maya-travel-agent
        annotations:
          summary: "High API response time detected"
          description: "API response time is above 3 seconds (95th percentile) for the last 5 minutes."

      # High error rate alerts
      - alert: HighErrorRate
        expr: rate(http_requests_total{status!~"2.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: critical
          service: maya-travel-agent
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for the last 5 minutes."

      # Memory usage alerts
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: maya-travel-agent
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for the last 5 minutes."

      # CPU usage alerts
      - alert: HighCPUUsage
        expr: (1 - avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance)) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: maya-travel-agent
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for the last 5 minutes."

      # Disk space alerts
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
        for: 5m
        labels:
          severity: critical
          service: maya-travel-agent
        annotations:
          summary: "Low disk space detected"
          description: "Available disk space is below 10% for the last 5 minutes."

      # Database connection alerts (if applicable)
      - alert: DatabaseConnectionIssue
        expr: mongodb_up == 0
        for: 2m
        labels:
          severity: critical
          service: mongodb
        annotations:
          summary: "Database connection issue"
          description: "Unable to connect to MongoDB for more than 2 minutes."

      # Service discovery health check
      - alert: HealthCheckFailed
        expr: health_check_status == 0
        for: 3m
        labels:
          severity: critical
          service: maya-travel-agent
        annotations:
          summary: "Health check failed"
          description: "Application health check has been failing for more than 3 minutes."