apiVersion: apps/v1
kind: Deployment
metadata:
  name: amrikyy-backend
  namespace: amrikyy-travel
  labels:
    app: amrikyy-backend
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: amrikyy-backend
  template:
    metadata:
      labels:
        app: amrikyy-backend
        component: api
    spec:
      containers:
      - name: backend
        image: amrikyy-travel/backend:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: amrikyy-secrets
              key: supabase-url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: amrikyy-secrets
              key: supabase-anon-key
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: amrikyy-secrets
              key: supabase-service-role-key
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: amrikyy-secrets
              key: telegram-bot-token
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: amrikyy-secrets
              key: stripe-secret-key
        - name: ZAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: amrikyy-secrets
              key: zai-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - amrikyy-backend
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: amrikyy-backend-service
  namespace: amrikyy-travel
  labels:
    app: amrikyy-backend
spec:
  selector:
    app: amrikyy-backend
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amrikyy-frontend
  namespace: amrikyy-travel
  labels:
    app: amrikyy-frontend
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amrikyy-frontend
  template:
    metadata:
      labels:
        app: amrikyy-frontend
        component: web
    spec:
      containers:
      - name: frontend
        image: amrikyy-travel/frontend:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: VITE_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: amrikyy-secrets
              key: supabase-url
        - name: VITE_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: amrikyy-secrets
              key: supabase-anon-key
        - name: VITE_STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: amrikyy-secrets
              key: stripe-publishable-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: amrikyy-frontend-service
  namespace: amrikyy-travel
  labels:
    app: amrikyy-frontend
spec:
  selector:
    app: amrikyy-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amrikyy-ingress
  namespace: amrikyy-travel
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.amrikyy-travel-agent.com
    - app.amrikyy-travel-agent.com
    secretName: amrikyy-tls
  rules:
  - host: api.amrikyy-travel-agent.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: amrikyy-backend-service
            port:
              number: 80
  - host: app.amrikyy-travel-agent.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: amrikyy-frontend-service
            port:
              number: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amrikyy-config
  namespace: amrikyy-travel
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      - job_name: 'amrikyy-backend'
        static_configs:
          - targets: ['amrikyy-backend-service:80']
        metrics_path: '/metrics'
        scrape_interval: 5s

      - job_name: 'amrikyy-frontend'
        static_configs:
          - targets: ['amrikyy-frontend-service:80']
        scrape_interval: 15s

---
apiVersion: v1
kind: Secret
metadata:
  name: amrikyy-secrets
  namespace: amrikyy-travel
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  supabase-url: <base64-encoded-url>
  supabase-anon-key: <base64-encoded-key>
  supabase-service-role-key: <base64-encoded-key>
  telegram-bot-token: <base64-encoded-token>
  stripe-secret-key: <base64-encoded-key>
  stripe-publishable-key: <base64-encoded-key>
  zai-api-key: <base64-encoded-key>

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amrikyy-storage
  namespace: amrikyy-travel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: amrikyy-backend-pdb
  namespace: amrikyy-travel
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: amrikyy-backend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: amrikyy-backend-hpa
  namespace: amrikyy-travel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: amrikyy-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80