apiVersion: 1

# List of data sources to delete when Grafana starts
deleteDatasources:
  - name: Prometheus
    orgId: 1

# List of data sources to create/update
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
      queryTimeout: "60s"
      tlsSkipVerify: false
      manageAlerts: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      tlsSkipVerify: false
      manageAlerts: true

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: true
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true