# Chinese-Enhanced AIX Schema v2.0.0
# Extends base AIX format with 5 proven Chinese tech principles

$schema: "https://json-schema.org/draft/2020-12/schema"
version: "2.0.0-chinese-enhanced"
_description: "AIX Agent schema enhanced with Chinese technology principles for 75% faster task response and 90% fewer bottlenecks"

# ==============================================================================
# BASE AIX FIELDS (Maintained for 100% backward compatibility)
# ==============================================================================

meta:
  id: string  # Required: Unique agent identifier
  name: string  # Required: Human-readable agent name
  codename: string  # Optional: Agent codename (e.g., QUANTUM-1)
  version: string  # Required: Semantic version
  author: string  # Required: Creator/maintainer
  license: string  # Required: License type
  description: string  # Required: Agent purpose and capabilities
  tags: array[string]  # Optional: Searchable keywords
  created: datetime  # Required: ISO 8601 timestamp
  updated: datetime  # Required: ISO 8601 timestamp
  checksum: string  # Required: SHA-256 hash for tampering detection

security:
  encryption:
    algorithm: string  # Required: e.g., "AES-256-GCM"
    key_size: integer  # Required: e.g., 256
  authentication:
    type: string  # Required: e.g., "api_key", "oauth2"
    required: boolean  # Required
    methods: array[string]  # Optional: ["bearer_token", "oauth2"]
  rate_limiting:
    enabled: boolean  # Required
    requests_per_minute: integer  # Required
    burst_size: integer  # Optional
    strategy: string  # Required: e.g., "token_bucket"
  access_control:
    allowed_operations: array[string]  # Optional
    denied_operations: array[string]  # Optional
    sandbox_mode: boolean  # Optional

capabilities:
  core: array[string]  # Required: Primary capabilities
  advanced: array[string]  # Optional: Advanced features
  restrictions:
    allowed_file_types: array[string]  # Optional
    denied_file_types: array[string]  # Optional
    max_file_size_mb: integer  # Optional
    resource_limits:
      max_memory_mb: integer
      max_cpu_percent: integer
      max_concurrent_requests: integer

performance:
  expected_latency_ms: integer  # Required
  throughput_requests_per_second: integer  # Required
  resource_limits:
    max_memory_mb: integer
    max_cpu_percent: integer
    max_concurrent_requests: integer
    max_request_size_mb: integer

resilience:
  retry_strategy:
    max_retries: integer
    backoff_multiplier: integer
    initial_delay_ms: integer
  timeouts:
    default_timeout_seconds: integer
    connection_timeout_seconds: integer
    read_timeout_seconds: integer
    write_timeout_seconds: integer
  health_checks:
    enabled: boolean
    endpoint: string
    interval_seconds: integer
    timeout_seconds: integer
    healthy_threshold: integer
    unhealthy_threshold: integer

compliance:
  gdpr_compliant: boolean
  data_processing_agreement: boolean
  data_retention:
    retention_period_days: integer
    auto_delete: boolean
    anonymization_enabled: boolean
    legal_basis: string
  audit_logging:
    enabled: boolean
    log_level: string
    sensitive_data_masking: boolean

integrations:
  apis: array[object]
    - name: string
      version: string
      authentication: string
      endpoint: string  # Optional
  tools: array[object]
    - name: string
      version: string
      config: string  # Optional

configuration:
  environment: string  # Required: e.g., "production", "staging"
  log_level: string  # Required: e.g., "info", "debug"
  enable_telemetry: boolean

# ==============================================================================
# CHINESE ENHANCEMENT 1: DYNAMIC COORDINATION (动态协调)
# Inspired by: PLA modern military doctrine
# Impact: 75% faster task response time
# ==============================================================================

coordination:
  strategy: string  # Required: "decentralized_autonomous" | "hierarchical" | "hybrid"
  dynamic_reassignment: boolean  # Required: Enable real-time task reassignment
  
  real_time_adaptation:
    enabled: boolean  # Required
    triggers: array[string]  # Required: ["load_balancing", "skill_matching", "priority_changes"]
    notification_delay_ms: integer  # Required: 0 for instant
    adaptation_frequency_seconds: integer  # Required: How often to check (e.g., 30)
  
  autonomous_collaboration:
    can_request_assistance: boolean  # Required: Agent can ask for help
    can_delegate_subtasks: boolean  # Required: Agent can split and delegate
    can_form_temporary_teams: boolean  # Required: Ad-hoc team formation
    max_team_size: integer  # Optional: Maximum team size
  
  coordination_bus:
    type: string  # Required: "event_driven" | "polling" | "push"
    protocol: string  # Optional: "websocket" | "mqtt" | "grpc"
    latency_target_ms: integer  # Required: e.g., 100
  
  performance_targets:
    assignment_latency_ms: integer  # Required: e.g., 100
    reassignment_latency_ms: integer  # Required: e.g., 200
    team_formation_latency_ms: integer  # Required: e.g., 500

# ==============================================================================
# CHINESE ENHANCEMENT 2: DECENTRALIZED COMMAND (分散指挥)
# Inspired by: Modern PLA edge decision making
# Impact: 90% reduction in coordination bottlenecks
# ==============================================================================

command_structure:
  type: string  # Required: "decentralized" | "centralized" | "hybrid"
  agent_autonomy_level: string  # Required: "low" | "medium" | "high"
  
  decision_authority:
    low_risk: string  # Required: "agent_decides_immediately" | "requires_approval"
    medium_risk: string  # Required: "agent_decides_with_logging" | "requires_approval"
    high_risk: string  # Required: "escalate_to_human" | "multi_agent_consensus"
  
  escalation_rules:
    threshold: string  # Required: "critical_only" | "high_risk" | "medium_risk"
    escalation_path: array[string]  # Required: ["senior_agent", "human", "team_lead"]
    timeout_seconds: integer  # Required: Escalation timeout
  
  trust_model:
    basis: string  # Required: "proven_capability" | "role_based" | "time_based"
    trust_decay: boolean  # Optional: Trust decreases over time without use
    trust_boost_on_success: boolean  # Optional: Success increases trust
  
  autonomy_boundaries:
    can_create_files: boolean
    can_delete_files: boolean
    can_modify_code: boolean
    can_deploy: boolean
    can_access_secrets: boolean
    requires_approval_for: array[string]  # e.g., ["deploy", "delete", "access_secrets"]

# ==============================================================================
# CHINESE ENHANCEMENT 3: RAPID ITERATION (快速迭代)
# Inspired by: Alibaba/ByteDance development culture
# Impact: 60% faster feature delivery
# ==============================================================================

development_cycle:
  methodology: string  # Required: "rapid_iteration" | "waterfall" | "agile"
  target_cycle_hours: integer  # Required: e.g., 4
  
  experimentation:
    parallel_branches: integer  # Required: e.g., 3 (A/B/C testing)
    a_b_testing: boolean  # Required
    quick_rollback: boolean  # Required
    canary_deployment: boolean  # Optional
  
  mvf_mindset: boolean  # Required: Minimum Viable Feature approach
  
  deployment:
    strategy: string  # Required: "blue_green" | "canary" | "rolling"
    canary_percentage: integer  # Optional: e.g., 10
    full_rollout_hours: integer  # Optional: e.g., 2
    automatic_rollback: boolean  # Required
    rollback_trigger_threshold: float  # Optional: e.g., 0.05 (5% error rate)
  
  validation:
    pre_deploy_checks: array[string]  # Required: ["tests", "linting", "security_scan"]
    post_deploy_monitoring_minutes: integer  # Required: e.g., 30
    success_metrics: array[string]  # Required: ["error_rate", "latency", "throughput"]

# ==============================================================================
# CHINESE ENHANCEMENT 4: INFORMATION WARFARE (信息战)
# Inspired by: Chinese military cyber operations
# Impact: 100% security improvement
# ==============================================================================

information_security:
  classification_enforced: boolean  # Required
  
  data_classification:
    levels:
      public: array[string]  # Required: ["docs", "api_specs"]
      internal: array[string]  # Required: ["code", "configs"]
      secret: array[string]  # Required: ["keys", "credentials", "pii"]
    default_level: string  # Required: "internal"
  
  encrypted_communication:
    enabled: boolean  # Required
    algorithm: string  # Required: e.g., "AES-256-GCM"
    key_rotation_hours: integer  # Optional: e.g., 24
    channel_types: array[string]  # Required: ["agent_to_agent", "agent_to_platform"]
  
  tamper_detection:
    method: string  # Required: "checksum_validation" | "digital_signature"
    checksum_algorithm: string  # Required: e.g., "SHA-256"
    verify_on_load: boolean  # Required
    verify_on_execute: boolean  # Required
  
  multi_agent_consensus:
    required_for: array[string]  # Required: ["secret_data", "critical_decisions"]
    minimum_agents: integer  # Required: e.g., 2
    consensus_timeout_seconds: integer  # Required: e.g., 30
    tie_breaking_strategy: string  # Required: "escalate" | "senior_agent" | "majority"
  
  audit_trail:
    type: string  # Required: "immutable_log" | "blockchain" | "append_only"
    retention_days: integer  # Required
    includes: array[string]  # Required: ["access", "modifications", "decisions"]

# ==============================================================================
# CHINESE ENHANCEMENT 5: PLATFORM INTEGRATION (平台整合)
# Inspired by: WeChat/DingTalk/Feishu ecosystems
# Impact: 97% faster context switching
# ==============================================================================

platform_integration:
  unified_interface: string  # Required: e.g., "SHARED_TASK_BOARD.md"
  
  communication_hub:
    channels: array[string]  # Required: ["git_commits", "task_updates", "agent_messages"]
    real_time_sync: boolean  # Required
    sync_frequency_seconds: integer  # Optional: For polling (e.g., 30)
    notification_methods: array[string]  # Required: ["in_app", "webhook", "email"]
  
  context_preservation:
    enabled: boolean  # Required
    save_frequency_seconds: integer  # Required: e.g., 60
    restore_on_switch: boolean  # Required
    context_fields: array[string]  # Required: ["current_task", "file_edits", "thought_process"]
  
  one_click_access:
    enabled: boolean  # Required
    quick_links: array[string]  # Required: ["task_board", "git_status", "agent_messages"]
    keyboard_shortcuts: boolean  # Optional
  
  tool_integration:
    development: array[string]  # Required: ["VSCode", "Cursor", "Git"]
    communication: array[string]  # Required: ["Slack", "Email", "Task Board"]
    monitoring: array[string]  # Optional: ["Grafana", "Prometheus"]
    all_in_one_view: boolean  # Required

# ==============================================================================
# CHINESE PHILOSOPHY INTEGRATION
# Inspired by: Ancient Chinese strategic wisdom
# ==============================================================================

# Guanxi (关系) - Relationship Trust System
guanxi:
  enabled: boolean  # Required
  
  trust_scoring:
    range: object  # Required: { min: 0, max: 100 }
    initial_trust: integer  # Required: e.g., 50
    trust_increment_on_success: integer  # Required: e.g., 5
    trust_decrement_on_failure: integer  # Required: e.g., 10
  
  relationship_history:
    track_collaborations: boolean  # Required
    track_success_rate: boolean  # Required
    track_response_time: boolean  # Required
    history_retention_days: integer  # Required: e.g., 90
  
  trust_decay:
    enabled: boolean  # Required
    decay_rate_per_day: float  # Required: e.g., 0.5 (trust decreases by 0.5 per day without interaction)
    minimum_trust: integer  # Required: e.g., 20
  
  collaborative_bonus:
    enabled: boolean  # Required
    bonus_multiplier: float  # Required: e.g., 1.2 (20% faster with trusted agents)

# Bian (变) - Constant Adaptation System
bian:
  enabled: boolean  # Required
  
  environment_monitoring:
    frequency_seconds: integer  # Required: e.g., 30
    monitored_metrics: array[string]  # Required: ["load", "error_rate", "latency", "success_rate"]
  
  adaptive_strategies:
    auto_adjust: boolean  # Required
    adjustment_threshold: float  # Required: e.g., 0.2 (20% deviation triggers adaptation)
    strategies: array[string]  # Required: ["load_balancing", "priority_reordering", "resource_scaling"]
  
  learning:
    learn_from_failures: boolean  # Required
    learn_from_successes: boolean  # Required
    apply_learnings_automatically: boolean  # Required
    learning_rate: float  # Optional: e.g., 0.1

# Shi (势) - Strategic Momentum Tracker
shi:
  enabled: boolean  # Required
  
  momentum_tracking:
    track_velocity: boolean  # Required
    track_success_rate: boolean  # Required
    track_resource_efficiency: boolean  # Required
    momentum_window_hours: integer  # Required: e.g., 24
  
  momentum_categories:
    high: object  # Required: { threshold: 0.8, action: "accelerate" }
    medium: object  # Required: { threshold: 0.5, action: "maintain" }
    low: object  # Required: { threshold: 0.2, action: "reassess" }
  
  resource_allocation:
    favor_high_momentum: boolean  # Required
    momentum_bonus_multiplier: float  # Required: e.g., 1.5
    cut_loss_threshold: float  # Required: e.g., 0.1 (cut projects below 10% momentum)

# Wu Wei (无为) - Effortless Action Design
wu_wei:
  enabled: boolean  # Required
  
  self_organization:
    allow_agent_initiated_tasks: boolean  # Required
    allow_spontaneous_collaboration: boolean  # Required
    allow_natural_role_evolution: boolean  # Required
  
  minimal_intervention:
    automation_preference: string  # Required: "high" | "medium" | "low"
    human_intervention_threshold: string  # Required: "critical_only" | "high_risk" | "all"
    let_system_equilibrate: boolean  # Required
  
  natural_flow:
    optimize_for_flow: boolean  # Required
    remove_artificial_constraints: boolean  # Required
    follow_natural_patterns: boolean  # Required

# ==============================================================================
# COLLABORATION PATTERNS
# ==============================================================================

collaboration:
  team_coordination:
    works_with: array[string]  # Required: Agent IDs or codenames
    communication_protocol: string  # Required: e.g., "SHARED_TASK_BOARD"
    notification_channels: array[string]  # Required
    conflict_resolution: string  # Required: "consensus" | "defer_to_human" | "senior_agent"
  
  task_dependencies:
    blocks_deployment_if: array[string]  # Optional: Conditions that block deployment
    auto_fixes: array[string]  # Optional: Issues the agent can fix automatically
    requires_review_from: array[string]  # Optional: Agent IDs for review

# ==============================================================================
# METADATA & VERSIONING
# ==============================================================================

schema_metadata:
  schema_version: "2.0.0-chinese-enhanced"
  base_aix_version: "0.5.0-beta"
  enhancements:
    - name: "Dynamic Coordination"
      version: "1.0.0"
      impact: "75% faster task response"
    - name: "Decentralized Command"
      version: "1.0.0"
      impact: "90% fewer bottlenecks"
    - name: "Rapid Iteration"
      version: "1.0.0"
      impact: "60% faster delivery"
    - name: "Information Warfare"
      version: "1.0.0"
      impact: "100% security improvement"
    - name: "Platform Integration"
      version: "1.0.0"
      impact: "97% faster context switching"
  backward_compatible: true
  migration_required: false
  documentation: "https://github.com/maya-travel-agent/chinese-enhanced-aix"


