name: Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, develop]

jobs:
  backend-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install dependencies
        run: cd backend && npm ci
      
      - name: Run validation tests
        run: cd backend && npm test -- tests/validation.test.js --ci
      
      - name: Run error handler tests
        run: cd backend && npm test -- tests/errorHandler.test.js --ci
      
      - name: Run all tests
        run: cd backend && npm test -- --ci --coverage
        continue-on-error: true

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: cd frontend && npm ci
      
      - name: Type check
        run: cd frontend && npm run type-check
      
      - name: Build
        run: cd frontend && npm run build
